export const HeaderNavs = [
    {
        id:1,
        text:'Home',
        href:'#hero'
    },
    {
        id:2,
        text:'About',
        href:'#about'
    },
    {
        id:3,
        text:'Services',
        href:'#services'
    },
    {
        id:4,
        text:'Portfolio',
        href:'#projects'
    },
    {
        id:5,
        text:'Testimonials',
        href:'#testimonials'
    },
    {
        id:6,
        text:'Faqs',
        href:'#faq'
    },
]